name: actionlint

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/*.{yml,yaml}"
  pull_request:
    paths:
      - ".github/workflows/*.{yml,yaml}"

jobs:
  actionlint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Cache aqua dir
        uses: actions/cache@v4.0.0
        with:
          path: ~/.local/share/aquaproj-aqua
          key: aqua-installer-${{ hashFiles('aqua.yaml') }}
          restore-keys: |
            aqua-installer-
      - name: Setup aqua
        uses: aquaproj/aqua-installer@v2.2.0
        with:
          aqua_version: v2.21.3
          aqua_opts: ""
      - name: Run actionlint
        run: actionlint -color
