name: actionlint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  actionlint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          filters: |
            target:
              - '.github/workflows/*.{yml,yaml}'
      - name: Cache aqua dir
        uses: actions/cache@v4.0.0
        with:
          path: ~/.local/share/aquaproj-aqua
          key: aqua-installer-${{ hashFiles('aqua.yaml') }}
          restore-keys: |
            aqua-installer-
        if: steps.changes.outputs.target == 'true'
      - name: Setup aqua
        uses: aquaproj/aqua-installer@v2.2.0
        with:
          aqua_version: v2.21.3
          aqua_opts: ""
        if: steps.changes.outputs.target == 'true'
      - name: Run actionlint
        run: actionlint -color
        if: steps.changes.outputs.target == 'true'
