name: markdownlint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  markdownlint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Set $NODE_VERSION
        run: echo "NODE_VERSION=$(jq -r '.volta.node' < package.json)" >> "$GITHUB_ENV"
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Run markdownlint
        run: npx markdownlint-cli2 '*.{md,markdown}'
