name: prettier

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Install aqua
        uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.36.1
      - name: Cache ~/.npm
        uses: "actions/cache@2cdf405574d6ef1f33a1d12acccd3ae82f47b3f2" # v4.1.0
        with:
          path: ~/.npm
          key: node-cache-${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
      - name: Run npm ci
        run: npm ci
      - name: Run prettier
        run: npx prettier --check .
