name: prettier

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-diff:
    runs-on: ubuntu-22.04
    outputs:
      target: ${{ steps.changes.outputs.target == 'true' }}
    steps:
      - uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          filters: |
            target:
              - '**/*.{json,yml,yaml,md,markdown}'

  prettier:
    runs-on: ubuntu-22.04
    needs: [check-diff]
    if: needs.check-diff.outputs.target == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Set $NODE_VERSION
        run: echo "NODE_VERSION=$(jq -r '.volta.node' < package.json)" >> "$GITHUB_ENV"
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Run prettier
        run: npx prettier --check .
