name: renovate-config-validator

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  renovate-config-validator:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Run renovate-config-validator
        uses: suzuki-shunsuke/github-action-renovate-config-validator@v1.0.1
