name: renovate-config-validator

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  renovate-config-validator:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          filters: |
            target:
              - '**/renovate.json'
      - name: Run renovate-config-validator
        uses: suzuki-shunsuke/github-action-renovate-config-validator@v1.0.1
        if: steps.changes.outputs.target == 'true'
