name: terraform

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  pull-requests: write

jobs:
  check-diff:
    runs-on: ubuntu-22.04
    outputs:
      target: ${{ steps.changes.outputs.target == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            target:
              - 'terraform/**/*'
              - '.github/workflows/terraform.yml'

  terraform-fmt:
    runs-on: ubuntu-22.04
    needs: [check-diff]
    if: needs.check-diff.outputs.target == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - name: Setup aqua
        uses: aquaproj/aqua-installer@4551ec64e21bf0f557c2525135ff0bd2cba40ec7 # v3.0.0
        with:
          aqua_version: v2.27.3
      - name: Run terraform fmt
        working-directory: "./terraform"
        run: terraform fmt -check -recursive

  terraform-validate:
    name: terraform-validate (${{ matrix.dir }})
    runs-on: ubuntu-22.04
    needs: [check-diff]
    if: needs.check-diff.outputs.target == 'true'
    strategy:
      matrix:
        include:
          - { dir: koyashi.ro, prefix: KOYASHI_RO }
          - { dir: koyashiro.com, prefix: KOYASHIRO_COM }
          - { dir: koyashiro.dev, prefix: KOYASHIRO_DEV }
          - { dir: koyashiro.jp, prefix: KOYASHIRO_JP }
          - { dir: koyashiro.live, prefix: KOYASHIRO_LIVE }
          - { dir: koyashiro.me, prefix: KOYASHIRO_ME }
          - { dir: koyashiro.net, prefix: KOYASHIRO_NET }
          - { dir: koyashiro.sh, prefix: KOYASHIRO_SH }
    env:
      TF_WORKSPACE: ${{ secrets[format('TF_WORKSPACE_{0}', matrix.prefix)] }}
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - name: Setup aqua
        uses: aquaproj/aqua-installer@4551ec64e21bf0f557c2525135ff0bd2cba40ec7 # v3.0.0
        with:
          aqua_version: v2.27.3
      - name: Export secrets
        uses: koyashiro/export-secrets@0e3cbdb91bd369c3b3a4ebf68b5975662801f6a8 # v0.5.0
        with:
          secrets: ${{ toJSON(secrets) }}
          downcase-tf-var: true
          downcase-tf-token: true
      - name: Run terraform init
        working-directory: "./terraform/${{ matrix.dir }}"
        run: terraform init
      - name: Run terraform validate
        working-directory: "./terraform/${{ matrix.dir }}"
        run: terraform validate

  tflint:
    runs-on: ubuntu-22.04
    needs: [check-diff]
    if: needs.check-diff.outputs.target == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - name: Setup aqua
        uses: aquaproj/aqua-installer@4551ec64e21bf0f557c2525135ff0bd2cba40ec7 # v3.0.0
        with:
          aqua_version: v2.27.3
      - name: Cache tflint plugin dir
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('terraform/.tflint.hcl') }}
      - name: Init TFLint
        working-directory: "./terraform"
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run TFLint
        working-directory: "./terraform"
        run: tflint --recursive

  trivy:
    runs-on: ubuntu-22.04
    needs: [check-diff]
    if: needs.check-diff.outputs.target == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - name: Setup aqua
        uses: aquaproj/aqua-installer@4551ec64e21bf0f557c2525135ff0bd2cba40ec7 # v3.0.0
        with:
          aqua_version: v2.27.3
      - name: Run Trivy
        run: trivy config .

  terraform-plan:
    name: terraform-plan (${{ matrix.dir }})
    runs-on: ubuntu-22.04
    needs: [check-diff]
    if: needs.check-diff.outputs.target == 'true'
    strategy:
      matrix:
        include:
          - { dir: koyashi.ro, prefix: KOYASHI_RO }
          - { dir: koyashiro.com, prefix: KOYASHIRO_COM }
          - { dir: koyashiro.dev, prefix: KOYASHIRO_DEV }
          - { dir: koyashiro.jp, prefix: KOYASHIRO_JP }
          - { dir: koyashiro.live, prefix: KOYASHIRO_LIVE }
          - { dir: koyashiro.me, prefix: KOYASHIRO_ME }
          - { dir: koyashiro.net, prefix: KOYASHIRO_NET }
          - { dir: koyashiro.sh, prefix: KOYASHIRO_SH }
    env:
      TF_WORKSPACE: ${{ secrets[format('TF_WORKSPACE_{0}', matrix.prefix)] }}
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - name: Setup aqua
        uses: aquaproj/aqua-installer@4551ec64e21bf0f557c2525135ff0bd2cba40ec7 # v3.0.0
        with:
          aqua_version: v2.27.3
      - name: Export secrets
        uses: koyashiro/export-secrets@0e3cbdb91bd369c3b3a4ebf68b5975662801f6a8 # v0.5.0
        with:
          secrets: ${{ toJSON(secrets) }}
          downcase-tf-var: true
          downcase-tf-token: true
      - name: Run terraform init
        working-directory: "./terraform/${{ matrix.dir }}"
        run: terraform init
      - name: Run terraform plan
        working-directory: "./terraform/${{ matrix.dir }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: tfcmt -var target:${{ matrix.dir }} plan -patch -- terraform plan -no-color

  terraform-apply:
    name: terraform-apply (${{ matrix.dir }})
    runs-on: ubuntu-22.04
    needs: [check-diff, terraform-plan]
    if: needs.check-diff.outputs.target == 'true' && github.ref == 'refs/heads/main'
    strategy:
      matrix:
        include:
          - { dir: koyashi.ro, prefix: KOYASHI_RO }
          - { dir: koyashiro.com, prefix: KOYASHIRO_COM }
          - { dir: koyashiro.dev, prefix: KOYASHIRO_DEV }
          - { dir: koyashiro.jp, prefix: KOYASHIRO_JP }
          - { dir: koyashiro.live, prefix: KOYASHIRO_LIVE }
          - { dir: koyashiro.me, prefix: KOYASHIRO_ME }
          - { dir: koyashiro.net, prefix: KOYASHIRO_NET }
          - { dir: koyashiro.sh, prefix: KOYASHIRO_SH }
    env:
      TF_WORKSPACE: ${{ secrets[format('TF_WORKSPACE_{0}', matrix.prefix)] }}
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - name: Setup aqua
        uses: aquaproj/aqua-installer@4551ec64e21bf0f557c2525135ff0bd2cba40ec7 # v3.0.0
        with:
          aqua_version: v2.27.3
      - name: Export secrets
        uses: koyashiro/export-secrets@0e3cbdb91bd369c3b3a4ebf68b5975662801f6a8 # v0.5.0
        with:
          secrets: ${{ toJSON(secrets) }}
          downcase-tf-var: true
          downcase-tf-token: true
      - name: Run terraform init
        working-directory: "./terraform/${{ matrix.dir }}"
        run: terraform init
      - name: Run terraform apply
        working-directory: "./terraform/${{ matrix.dir }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: tfcmt -var target:${{ matrix.dir }} apply -- terraform apply -auto-approve -no-color
