name: terraform

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  pull-requests: write

env:
  TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
  TF_WORKSPACE: ${{ secrets.TF_WORKSPACE }}
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

jobs:
  check-diff:
    runs-on: ubuntu-22.04
    outputs:
      target: ${{ steps.changes.outputs.target == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - uses: dorny/paths-filter@v2.12.0
        id: changes
        with:
          filters: |
            target:
              - 'terraform/**/*'

  terraform-fmt:
    runs-on: ubuntu-22.04
    needs: [check-diff]
    if: needs.check-diff.outputs.target == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Cache aqua dir
        uses: actions/cache@v4.0.0
        with:
          path: ~/.local/share/aquaproj-aqua
          key: aqua-installer-${{ hashFiles('aqua.yaml') }}
          restore-keys: |
            aqua-installer-
      - name: Setup aqua
        uses: aquaproj/aqua-installer@v2.2.0
        with:
          aqua_version: v2.21.3
          aqua_opts: ""
      - name: Run terraform fmt
        working-directory: "./terraform"
        run: terraform fmt -check -recursive

  terraform-validate:
    runs-on: ubuntu-22.04
    needs: [check-diff]
    if: needs.check-diff.outputs.target == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Cache aqua dir
        uses: actions/cache@v4.0.0
        with:
          path: ~/.local/share/aquaproj-aqua
          key: aqua-installer-${{ hashFiles('aqua.yaml') }}
          restore-keys: |
            aqua-installer-
      - name: Setup aqua
        uses: aquaproj/aqua-installer@v2.2.0
        with:
          aqua_version: v2.21.3
          aqua_opts: ""
      - name: Run terraform init
        working-directory: "./terraform"
        run: terraform init
      - name: Run terraform validate
        working-directory: "./terraform"
        run: terraform validate

  tflint:
    runs-on: ubuntu-22.04
    needs: [check-diff]
    if: needs.check-diff.outputs.target == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Cache aqua dir
        uses: actions/cache@v4.0.0
        with:
          path: ~/.local/share/aquaproj-aqua
          key: aqua-installer-${{ hashFiles('aqua.yaml') }}
          restore-keys: |
            aqua-installer-
      - name: Setup aqua
        uses: aquaproj/aqua-installer@v2.2.0
        with:
          aqua_version: v2.21.3
          aqua_opts: ""
      - name: Cache tflint plugin dir
        uses: actions/cache@v4.0.0
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('terraform/.tflint.hcl') }}
          restore-keys: |
            tflint-
      - name: Init TFLint
        working-directory: "./terraform"
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Run TFLint
        working-directory: "./terraform"
        run: tflint -f compact

  terraform-plan:
    runs-on: ubuntu-22.04
    needs: [check-diff]
    if: needs.check-diff.outputs.target == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Cache aqua dir
        uses: actions/cache@v4.0.0
        with:
          path: ~/.local/share/aquaproj-aqua
          key: aqua-installer-${{ hashFiles('aqua.yaml') }}
          restore-keys: |
            aqua-installer-
      - name: Setup aqua
        uses: aquaproj/aqua-installer@v2.2.0
        with:
          aqua_version: v2.21.3
          aqua_opts: ""
      - name: Run terraform init
        working-directory: "./terraform"
        run: terraform init
      - name: Run terraform plan
        working-directory: "./terraform"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: tfcmt plan -patch -- terraform plan -no-color

  terraform-apply:
    runs-on: ubuntu-22.04
    needs: [check-diff, terraform-plan]
    if: needs.check-diff.outputs.target == 'true' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Cache aqua dir
        uses: actions/cache@v4.0.0
        with:
          path: ~/.local/share/aquaproj-aqua
          key: aqua-installer-${{ hashFiles('aqua.yaml') }}
          restore-keys: |
            aqua-installer-
      - name: Setup aqua
        uses: aquaproj/aqua-installer@v2.2.0
        with:
          aqua_version: v2.21.3
          aqua_opts: ""
      - name: Run terraform init
        working-directory: "./terraform"
        run: terraform init
      - name: Run terraform apply
        working-directory: "./terraform"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: tfcmt apply -- terraform apply -auto-approve -no-color
